cinematografia/urls.py
from django.urls import path
from cinematografia import views
from .views import agregar_peli, agregar_series, about_me, prueba, detalle_pelicula, detalle_serie, perfil

urlpatterns = [
    
    path('', prueba, name='prueba'),
    path('pelicula/<int:pk>',detalle_pelicula,name='detalle_pelicula'),
    path('serie/<int:pk>',detalle_serie,name='detalle_serie'),
    path('peliculas/', views.Peliculas01.as_view(), name='peliculas'),
    path('series/', views.Series01.as_view(), name='series'),
    path('agregar_peli/', agregar_peli,name='agregar_peli'),
    path('agregar_series/', agregar_series,name='agregar_series'),
    path('about_me/', about_me,name= 'about_me'),
    path('<int:pk>/eliminar',views.EliminarPeli.as_view(),name='eliminar'),
    path('<int:pk>/eliminar_serie',views.EliminarSerie.as_view(),name='eliminar_serie'),
    path('pelicula/<int:pk>/editar', views.Editar.as_view(),name = 'editar'),
    path('serie/<int:pk>/editar_serie', views.EditarSerie.as_view(),name = 'editar_serie'),
    path('perfil/', perfil, name='perfil'),
    
    
    
    
]

inicio/urls.py
from django.urls import path


urlpatterns = [
    
    
    
]

iwatch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('',include('cinematografia.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinematografia/models.py
from django.db import models
import os
from django.contrib.auth.models import User


def upload_to():
    return os.path.join('media/')



class Peliculas(models.Model):
    titulo = models.CharField(max_length=255)
    subtitulo = models.CharField(max_length=255)
    img = models.ImageField(upload_to=upload_to(),null=True)
    cuerpo = models.CharField(max_length=9000)
    director = models.CharField(max_length=255)
    genero = models.CharField(max_length=255)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateField (auto_now_add=True)
    
class Series(models.Model):
    titulo = models.CharField(max_length=255)
    subtitulo = models.CharField(max_length=255)
    img = models.ImageField(upload_to=upload_to(),null=True)
    cuerpo = models.CharField(max_length=9000)
    director = models.CharField(max_length=255)
    genero = models.CharField(max_length=255)
    temporadas = models.DecimalField(decimal_places=1, max_digits=3)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateField (auto_now_add=True)
    

    

cinematografia/forms.py
from django import forms 
from .models import Peliculas, Series

class FormPelicula(forms.ModelForm):
    img = forms.ImageField(required=False)
    class Meta:
        model = Peliculas
        fields = ['titulo', 'subtitulo', 'img', 'cuerpo', 'director', 'genero']
        
class FormSeries(forms.ModelForm):
    img = forms.ImageField(required=False)
    class Meta:
        model = Series
        fields = ['titulo', 'subtitulo', 'img', 'cuerpo', 'director', 'genero', 'temporadas']
                


class BuscarPelis(forms.Form):
    peli = forms.CharField(max_length=20)
        

cinematografia/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from .models import Peliculas, Series
from .forms import FormPelicula, FormSeries
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.views.generic.edit import  DeleteView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin




class Peliculas01(ListView):
    model = Peliculas
    template_name = 'peliculas.html'
    
    

class Series01(ListView):
    model = Series
    template_name = 'series.html'
    
########

def prueba(request):
    peliculas = Peliculas.objects.all()
    series = Series.objects.all()
    items = list(peliculas)+list(series)
    for item in items: 
        item.is_pelicula = isinstance(item, Peliculas)
    paginator = Paginator(items,1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'prueba.html', context)


def detalle_pelicula(request, pk):
    pelicula = get_object_or_404(Peliculas, pk=pk) 
    return render(request, 'articulo_pelicula.html', {'pelicula':pelicula})


def detalle_serie(request, pk):
    serie = get_object_or_404(Series, pk=pk) 
    return render(request, 'articulo_serie.html', {'serie':serie})

    
        
@login_required(login_url='login')    
def agregar_peli(request):
    
    if request.method == 'POST':
        formulario = FormPelicula(request.POST,request.FILES)
        if formulario.is_valid():
            pelicula=formulario.save(commit=False)
            pelicula.usuario = request.user
            pelicula.save()
            return redirect('prueba')
    else: 
        formulario=FormPelicula()
    return render(request,'agregar_peli.html',{'formulario':formulario})



@login_required(login_url='login')    
def agregar_series(request):
    
    if request.method == 'POST':
        formulario = FormSeries(request.POST,request.FILES)
        if formulario.is_valid():
            pelicula=formulario.save(commit=False)
            pelicula.usuario = request.user
            pelicula.save()
            return redirect('prueba')
    else: 
        formulario=FormSeries()
    return render(request,'agregar_series.html',{'formulario':formulario})  


#######

def about_me(request):
    return render(request, 'about_me.html')

#######



class EliminarPeli(LoginRequiredMixin, UserPassesTestMixin ,DeleteView):
    model = Peliculas
    queryset = Peliculas.objects.all().order_by('-fecha')
    template_name = 'eliminar.html'
    success_url = reverse_lazy('peliculas')
    
    def test_func(self):
        pelicula = Peliculas.objects.get(id=self.kwargs.get('pk'))
        return self.request.user.id == pelicula.usuario.id



class EliminarSerie(LoginRequiredMixin, UserPassesTestMixin ,DeleteView):
    model = Series
    queryset = Series.objects.all().order_by('-fecha')
    template_name = 'eliminar.html'
    success_url = reverse_lazy('series')
    
    def test_func(self):
        serie = Series.objects.get(id=self.kwargs.get('pk'))
        return self.request.user.id == serie.usuario.id    


#########



class Editar(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Peliculas
    form_class = FormPelicula
    template_name = "editar.html"
    success_url = reverse_lazy('peliculas')
    
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super().form_valid(form)
    
    
    
    def test_func(self):
        pelicula = Peliculas.objects.get(id=self.kwargs.get('pk'))
        return self.request.user.id == pelicula.usuario.id
    

class EditarSerie(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Series
    form_class = FormSeries
    template_name = "editar.html"
    success_url = reverse_lazy('series')
    
    def form_valid(self, form):
        form.instance.usuario = self.request.user
        return super().form_valid(form)
    
    
    
    def test_func(self):
        serie = Series.objects.get(id=self.kwargs.get('pk'))
        return self.request.user.id == serie.usuario.id    



@login_required
def perfil(request):
    return render(request, 'perfil.html', {"user":request.user})
    
    




    
    
    
    

cinematografia/templates/about_me.html
{% extends "base.html" %}

{% block h1_header %}
<h1 style='font-style: oblique;'>Giuliano Acosta</h1>
{% endblock h1_header %}


{% block content %}
<h2 style='color: #4263cf;
    font-weight: bold;'>Creador de I Watch</h2>

<p style='font-size: 1.25rem;
    color: #ebecf0;'>Mi nombre es Giuliano y me estoy adentrando en el mundo de la programacion a traves del lenguaje python. Lenguaje el cual use para crear esta pagina y todo lo que ella contiene. ¿Qué es I Watch? Es un sitio donde personas de todo el mundo pueden leer y publicar reviews sobre sus peliculas y series favoritas, y no tan favoritas, un espacio hecho para compartir pensamientos, posturas, gustos y arte en general.
    La página cuneta con un inicio en el cual te apareceran reseñas de algunos perfiles sobre peliculas y series, también cuenta con una pestaña exclusivamente para películas y otra para series, en las cuales ademas de leer reseñas puedes publicar las tuyas siempre y cuando estes registrado.
    Si buscas expandir y compartir tu opinion con respecto a algunas obras del septimo arte, I Watch es la pagina ideal para tí.
</p>

{% endblock content %}

cinematografia/templates/agregar_peli.html
{% extends "base.html" %}

{% block main %}


{% block h1_header %}
Agregue su review
{% endblock h1_header %}


{% block content %}

<form method="post" enctype="multipart/form-data"> 
 {% csrf_token %}
 {{formulario.as_p}}
 <button type='submit'>Enviar</button>     
</form>

{% endblock content %}

{% endblock main %}

cinematografia/templates/agregar_series.html
{% extends "base.html" %}

{% block main %}


{% block h1_header %}
Agregue su review
{% endblock h1_header %}


{% block content %}

<form method="post" enctype="multipart/form-data"> 
 {% csrf_token %}
 {{formulario.as_p}}
 <button type='submit'>Enviar</button>     
</form>

{% endblock content %}

{% endblock main %}

cinematografia/templates/articulo_pelicula.html
{% extends "base.html" %}




{% block h1_header %}

{% endblock h1_header %}

{% block content %}
<div class='row d-flex justify-content-center' style='border:5px solid #802920; border-radius:40px;'>
    <div class='col-md-6 col-12 mx-auto mt-5 mb-5' style="text-align: center;">

<h3> {{pelicula.titulo}} </h3>
<h4> {{pelicula.subtitulo}} </h4>
{% if pelicula.img %}
<img src="{{pelicula.img.url}}" alt="">
{% endif %}
<p>{{pelicula.fecha}}</p>
<p>{{pelicula.usuario}}</p>
<p>{{pelicula.director}}</p>
<p>{{pelicula.genero}}</p>
<p>{{pelicula.cuerpo}}</p>


</div>
</div>





{% endblock content %}

cinematografia/templates/articulo_serie.html
{% extends "base.html" %}




{% block h1_header %}

{% endblock h1_header %}

{% block content %}

<div class='row d-flex justify-content-center' style='border:5px solid #802920; border-radius:40px;'>
    <div class='col-md-6 col-12 mx-auto mt-5 mb-5' style="text-align: center;">


<h3> {{serie.titulo}} </h3>
<h4> {{serie.subtitulo}} </h4>
{% if serie.img %}
<img src="{{serie.img.url}}" alt="">
{% endif %}
<p>{{serie.fecha}}</p>
<p>{{serie.usuario}}</p>
<p>{{serie.director}}</p>
<p>{{serie.genero}}</p>
<p>{{serie.cuerpo}}</p>


</div>
</div>





{% endblock content %}

cinematografia/templates/editar.html
{% extends "base.html" %}




{% block h1_header %}
Editar Reseña
{% endblock h1_header %}

{% block content %}
<div class="container mt-5" style='background-color: #21304a;border: 1px solid #dee2e6;border-radius: 15px;box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);'>
    <div class="row justify-content-center">
        <div class="col-md-6 col-11">
<form method="post" enctype = 'multipart/form-data' class=' p-4 rounded'>
    {% csrf_token %}
    {{form.as_p}}

    <button class='btn btn-outline-primary' type='submit' style=' border-radius: 20px;background-color: #4263cf;color: white;border: none;'> Subir </button>
    
     
</form>

</div>
</div>
</div>


{% endblock content %}

cinematografia/templates/eliminar.html
{% extends "base.html" %}




{% block h1_header %}
Eliminar reseña
{% endblock h1_header %}

{% block content %}


<h3>Estas segura que desas eliminar la reseña??? </h3>


<form method='post'> 
    {% csrf_token %}
    <button type='submit'> Si </button> 
<a href={% url "prueba" %}> No </a>

</form>


{% endblock content %}

cinematografia/templates/peliculas.html
{% extends "base.html" %}




{% block h1_header %}
<a style='color: #4263cf;font-weight: bold;text-decoration: none;border: 1px solid #4263cf;padding: 5px 20px;border-radius: 5px;display: inline-block;transition: background-color 0.3s, color 0.3s;'href={% url "agregar_peli" %}>Agregar review</a>
{% endblock h1_header %}

{% block content %}



{%for object in object_list%}
  <div class='row d-flex justify-content-center' style='border:5px solid #802920; border-radius:40px;'>
    <div class='col-md-6 col-12 mx-auto mt-5 mb-5' style="text-align: center;">
<h3> {{object.titulo}} </h3>
<h4> {{object.subtitulo}} </h4>
{% if object.img %}
<img src="{{object.img.url}}" height='500px' alt="">
{% endif %}
<p>{{object.fecha}}</p>
<p>{{object.usuario}}</p>
<p>{{object.director}}</p>
<p>{{object.genero}}</p>
<p>{{object.cuerpo}}</p>



{% if request.user.username == object.usuario.username %}

<a href={% url "eliminar" object.pk %}> Eliminar reseña </a>

<a href={% url "editar" object.pk %}> Editar reseña </a>

{% endif %}





    </div>
</div>
{%endfor%}



{% endblock content %}

cinematografia/templates/perfil.html
{% extends "base.html" %}

{% block content %}

<h1> Tu Perfil </h1>


<p>Usuario: {{user.username}}</p>
<p>Correo: {{user.email}}</p>
Titulos de tus reviews
<ul>
    {% for peliculas in user.peliculas_set.all %}
    <li>{{peliculas.titulo}}</li>
    
    
    {% endfor %}
</ul>









{% endblock content %}

cinematografia/templates/prueba.html
{% extends "base.html" %}



{% block content %}
<h1 class='fw-bolder'>  Listado de Películas y Series</h1>
<div class='row'>
<ul>
    {% for item in page_obj %}
      <div class='row d-flex justify-content-center' style='border:2px solid #4263cf; border-radius:40px;'>
    <div class='col-md-6 col-12 mx-auto mt-5 mb-5' style="text-align: center;">
        <li>
            <h2>{{ item.titulo }}</h2>
            <h3>{{ item.subtitulo }}</h3>
            <img src="{{ item.img.url }}" alt="{{ item.titulo }}" width=300px>
            <p>{{ item.cuerpo|truncatewords:50 }}</p>
            <p>Usuario: {{ item.usuario.username }}</p>
            <p>Fecha: {{ item.fecha }}</p>
            {% if item.is_pelicula %}
                <a href="{% url 'detalle_pelicula' item.pk %}">Leer más</a>
            {% else %}
                <a href="{% url 'detalle_serie' item.pk %}">Leer más</a>
            {% endif %}

        </li>
    </div>    
    </div>
    {% endfor %}
        
</ul>
</div>
<div>
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock content %}

cinematografia/templates/series.html
{% extends "base.html" %}




{% block h1_header %}
<a style='color: #4263cf;font-weight: bold;text-decoration: none;border: 1px solid #4263cf;padding: 5px 20px;border-radius: 5px;display: inline-block;transition: background-color 0.3s, color 0.3s;'href={% url "agregar_series" %}>Agregar review</a>
{% endblock h1_header %}

{% block content %}

{%for object in object_list%}
  <div class='row d-flex justify-content-center' style='border:5px solid #6a3d7d; border-radius:40px;'>
    <div class='col-md-6 col-12 mx-auto mt-5 mb-5' style="text-align: center;">

<h3> {{object.titulo}} </h3>
<h4> {{object.subtitulo}} </h4>
{% if object.img %}
<img src="{{object.img.url}}" height='500px' alt="">
{% endif %}
<p>{{object.fecha}}</p>
<p>{{object.usuario}}</p>
<p>{{object.director}}</p>
<p>{{object.genero}}</p>
<p>{{object.temporadas}}</p>
<p>{{object.cuerpo}}</p>



{% if request.user.username == object.usuario.username %}

<a href={% url "eliminar_serie" object.pk %}> Eliminar reseña </a>

<a href={% url "editar_serie" object.pk %}> Editar reseña </a>


{% endif %}




    </div>
</div>
{%endfor%}



{% endblock content %}